# Generated by Django 5.0 on 2023-12-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('conservation_status', models.CharField(choices=[('EN', 'Endangered'), ('VU', 'Vulnerable'), ('LC', 'Least Concern')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('climate', models.CharField(choices=[('TR', 'Tropical'), ('TE', 'Temperate'), ('AR', 'Arctic')], max_length=2)),
                ('area', models.IntegerField()),
                ('keepers', models.ManyToManyField(related_name='zones', to='zoo.keeper')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('diet', models.CharField(choices=[('CR', 'Carnivore'), ('HR', 'Herbivore'), ('OM', 'Omnivore')], max_length=2)),
                ('weight', models.FloatField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.species')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
